name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name : application.properties
      run: |
        mkdir -p src/main/resources
        echo "${{secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/applcation.properties
    - name : applcation-jwt.properties
      run: |
        echo "${{secrets.APPLICATION_JWT_PROPERTIES}}" > ./src/main/resources/applicaion-jwt.properties
    - name : application-s3.properties
      run: |
        echo "${{secrets.APPLICATION_S3_PROPERTIES}}" > ./src/main/resources/application-s3.properties
    - name : application-toss.properties
      run: |
        echo "${{secrets.APPLICATION_TOSS_PROPERTIES}}" > ./src/main/resources/application-toss.properties
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: 빌드된 파일 이름 변경하기
      run: mv ./build/libs/*SANPSHOT.jar .cicdtest.jar

    - name: SCP로 EC2에 빌드된 파일 전송하기
      uses : appleboy/scp-action@master
      with:
        host: ${{secrets.SERVER_IP}}
        username: ${{secrets.SSH_USER}}
        key : ${{secrets.SSH_PRIVATE_KEY}}
        source: cicdtest.jar
        target: /home/ubuntu

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
